services:
  cpp-app:
    container_name: streetParking
    command: ./streetParking
    environment:
      - TZ=Asia/Almaty
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_MODULE_LOADING=LAZY
    image: registry.parqour.com/cv/application/street-parking-cpp:v1.1-malay
    restart: always
    runtime: nvidia
    volumes:
      - ./config-unv.json:/app/config-unv.json
    logging:
      options:
        max-size: 50m
version: '2.3'
