services:
  street-parking:
    container_name: streetParking
    command: ./streetParking
    image: registry.infra.smartparking.kz/street-parking:v1.0.0
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./images:/app/images
    logging:
      options:
        max-size: 50m
version: '2.1'