services:
  cpp-app:
    container_name: streetParking
    command: ./streetParking
    environment:
      - TZ=Asia/Almaty
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_MODULE_LOADING=LAZY
    image: registry.infra.smartparking.kz/street-cpp-trt8:v1.0.0
    restart: always
    runtime: nvidia
    volumes:
      - ./config.json:/app/config.json
    logging:
      options:
        max-size: 50m
version: '2.3'
